#!/usr/bin/env node
/**
 * Extracts the neutral-ramp and extended-palette preset data out of the two
 * read-only reference pages in `.references/colors/` and writes the typed TS
 * data modules under `src/engine/presets/`.
 *
 * Both pages drive their tables from a `const rows = [...]` literal plus a
 * `<th data-col="N">` header row that maps column index -> preset name. We parse
 * exactly those two structures, so the committed TS is a 1:1 transcription and
 * nothing is eyeballed. Run with:
 *
 *     node scripts/extract-presets.mjs
 *
 * It is a build-time tool only — the app never parses HTML at runtime.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const COLORS = join(ROOT, ".references", "colors");
const OUT = join(ROOT, "src", "engine", "presets");

/** Pull the `const rows = [ ... ];` array literal out of a reference page. */
function parseRows(html) {
  const match = html.match(/const rows = (\[[\s\S]*?\n\]);/);
  if (!match) throw new Error("could not locate `const rows` literal");
  // The literal is plain JSON once the single trailing "•" markers are kept as
  // part of the string; JSON.parse handles it directly.
  const rows = JSON.parse(match[1].replace(/,(\s*[\]}])/g, "$1"));
  return rows.map(([name, ...cols]) => [name, cols.map(stripDerivedMarker)]);
}

/** `"#dd3687•"` marks a derived (interpolated) swatch — the bullet is not data. */
function stripDerivedMarker(value) {
  const hex = value.endsWith("•") ? value.slice(0, -1) : value;
  if (!/^#[0-9a-fA-F]{6}$/.test(hex)) throw new Error(`bad hex: ${value}`);
  return hex.toLowerCase();
}

/** Pull the `<th data-col="N">Label</th>` header cells, in document order. */
function parseHeader(html) {
  const headerRow = html.match(/<tr id="headerRow">([\s\S]*?)<\/tr>/);
  if (!headerRow) throw new Error("could not locate #headerRow");
  const cells = [...headerRow[1].matchAll(/<th data-col="(\d+)">([^<]+)<\/th>/g)];
  if (cells.length === 0) throw new Error("no data-col header cells");
  return cells.map(([, col, label]) => ({ col: Number(col), label: label.trim() }));
}

const banner = (source) => `// AUTO-GENERATED by scripts/extract-presets.mjs — do not edit by hand.
// Source: .references/colors/${source} (read-only reference material).
// Re-run \`node scripts/extract-presets.mjs\` to regenerate.
`;

// ---------------------------------------------------------------------------
// Neutral ramps
// ---------------------------------------------------------------------------

const neutralHtml = readFileSync(join(COLORS, "black-white-ramps.html"), "utf8");
const neutralRows = parseRows(neutralHtml);
const neutralHeader = parseHeader(neutralHtml);

// Ids are stable, URL-safe keys; the reference labels stay as display names.
const NEUTRAL_IDS = {
  "Home Assistant": "ha",
  "Rounded Theme": "rounded",
  "Slate (Tailwind)": "slate",
  "Gray (Tailwind)": "gray",
  "Zinc (Tailwind)": "zinc",
  "Stone (Tailwind)": "stone",
  "Mauve (Tailwind)": "mauve",
  "Olive (Tailwind)": "olive",
  "Mist (Tailwind)": "mist",
  "Taupe (Tailwind)": "taupe",
};

// "black" and "white" are the ramp's own 0 and 100 slots (real reference data,
// not synthesized — every column ships #000000 / #ffffff), not a name filtered
// out. See `NeutralRampSlot` in types.ts.
const slotRows = neutralRows.filter(
  ([name]) => name === "black" || name === "white" || name.startsWith("neutral-"),
);
const slotOf = (name) => (name === "black" ? 0 : name === "white" ? 100 : Number(name.slice("neutral-".length)));
const slots = slotRows.map(([name]) => slotOf(name));
const commentFor = (slot) => `neutral-${String(slot).padStart(2, "0")}`;

let out = banner("black-white-ramps.html");
out += `import type { NeutralRampPreset } from "../types.ts";\n\n`;
out += `export const NEUTRAL_RAMPS: readonly NeutralRampPreset[] = [\n`;
for (const { col, label } of neutralHeader) {
  const id = NEUTRAL_IDS[label];
  if (!id) throw new Error(`no id mapping for neutral ramp "${label}"`);
  out += `  {\n    id: "${id}",\n    label: ${JSON.stringify(label)},\n    ramp: {\n`;
  slotRows.forEach(([, cols], i) => {
    out += `      ${slots[i]}: "${cols[col]}", // ${commentFor(slots[i])}\n`;
  });
  out += `    },\n  },\n`;
}
out += `] as const;\n`;
writeFileSync(join(OUT, "neutral-ramps.ts"), out);
console.log(`neutral-ramps.ts: ${neutralHeader.length} presets x ${slotRows.length} slots`);

// ---------------------------------------------------------------------------
// Extended palettes
// ---------------------------------------------------------------------------

const paletteHtml = readFileSync(join(COLORS, "ha-color-palettes.html"), "utf8");
const paletteRows = parseRows(paletteHtml);
const paletteHeader = parseHeader(paletteHtml);

const PALETTE_IDS = {
  "Home Assistant": "ha",
  "Tailwind v3": "tailwind-v3",
  "Tailwind v4": "tailwind-v4",
  "Material Accent": "material-accent",
  "Ant Design": "ant-design",
  "Chakra UI": "chakra-ui",
  Bulma: "bulma",
  "Rounded Theme": "rounded",
};

out = banner("ha-color-palettes.html");
out += `import type { ExtendedPalettePreset } from "../types.ts";\n\n`;
out += `/** The 18 HA named colors, in the reference page's fixed hue order. */\n`;
out += `export const PALETTE_COLOR_NAMES = [\n`;
for (const [name] of paletteRows) out += `  "${name}",\n`;
out += `] as const;\n\n`;
out += `export const EXTENDED_PALETTES: readonly ExtendedPalettePreset[] = [\n`;
for (const { col, label } of paletteHeader) {
  const id = PALETTE_IDS[label];
  if (!id) throw new Error(`no id mapping for palette "${label}"`);
  out += `  {\n    id: "${id}",\n    label: ${JSON.stringify(label)},\n    colors: {\n`;
  for (const [name, cols] of paletteRows) {
    out += `      "${name}": "${cols[col]}",\n`;
  }
  out += `    },\n  },\n`;
}
out += `] as const;\n`;
writeFileSync(join(OUT, "palettes.ts"), out);
console.log(`palettes.ts: ${paletteHeader.length} presets x ${paletteRows.length} colors`);
