// AUTO-GENERATED by scripts/extract-presets.mjs — do not edit by hand.
// Source: .references/colors/black-white-ramps.html (read-only reference material).
// Re-run `node scripts/extract-presets.mjs` to regenerate.
import type { NeutralRampPreset } from "../types.ts";

export const NEUTRAL_RAMPS: readonly NeutralRampPreset[] = [
  {
    id: "ha",
    label: "Home Assistant",
    ramp: {
      5: "#141414", // neutral-05
      10: "#202020", // neutral-10
      20: "#363636", // neutral-20
      30: "#4a4a4a", // neutral-30
      40: "#5e5e5e", // neutral-40
      50: "#7a7a7a", // neutral-50
      60: "#989898", // neutral-60
      70: "#b1b1b1", // neutral-70
      80: "#cccccc", // neutral-80
      90: "#e6e6e6", // neutral-90
      95: "#f3f3f3", // neutral-95
    },
  },
  {
    id: "rounded",
    label: "Rounded Theme",
    ramp: {
      5: "#121418", // neutral-05
      10: "#1d2029", // neutral-10
      20: "#313642", // neutral-20
      30: "#454a57", // neutral-30
      40: "#595e6b", // neutral-40
      50: "#767a84", // neutral-50
      60: "#9498a3", // neutral-60
      70: "#acb1be", // neutral-70
      80: "#c7ccd8", // neutral-80
      90: "#e2e6ef", // neutral-90
      95: "#f1f3f9", // neutral-95
    },
  },
  {
    id: "slate",
    label: "Slate (Tailwind)",
    ramp: {
      5: "#0c1325", // neutral-05
      10: "#152034", // neutral-10
      20: "#29374c", // neutral-20
      30: "#3b4b62", // neutral-30
      40: "#4f5f77", // neutral-40
      50: "#6b7b93", // neutral-50
      60: "#8a9aaf", // neutral-60
      70: "#a4b3c6", // neutral-70
      80: "#c1cede", // neutral-80
      90: "#e0e7f0", // neutral-90
      95: "#eff4f9", // neutral-95
    },
  },
  {
    id: "gray",
    label: "Gray (Tailwind)",
    ramp: {
      5: "#0d1421", // neutral-05
      10: "#172030", // neutral-10
      20: "#2c3747", // neutral-20
      30: "#404b5b", // neutral-30
      40: "#555f6f", // neutral-40
      50: "#737a8a", // neutral-50
      60: "#9199a5", // neutral-60
      70: "#abb2bd", // neutral-70
      80: "#c7cdd5", // neutral-80
      90: "#e4e6eb", // neutral-90
      95: "#f2f3f6", // neutral-95
    },
  },
  {
    id: "zinc",
    label: "Zinc (Tailwind)",
    ramp: {
      5: "#141416", // neutral-05
      10: "#202023", // neutral-10
      20: "#35353b", // neutral-20
      30: "#494952", // neutral-30
      40: "#5d5d67", // neutral-40
      50: "#797983", // neutral-50
      60: "#9797a0", // neutral-60
      70: "#b0b0b8", // neutral-70
      80: "#cbcbd2", // neutral-80
      90: "#e6e6e8", // neutral-90
      95: "#f3f3f4", // neutral-95
    },
  },
  {
    id: "stone",
    label: "Stone (Tailwind)",
    ramp: {
      5: "#161412", // neutral-05
      10: "#231f1d", // neutral-10
      20: "#3a3532", // neutral-20
      30: "#4e4944", // neutral-30
      40: "#635d57", // neutral-40
      50: "#7f7974", // neutral-50
      60: "#9d9792", // neutral-60
      70: "#b5b0ac", // neutral-70
      80: "#d0cbc8", // neutral-80
      90: "#e8e6e4", // neutral-90
      95: "#f4f3f2", // neutral-95
    },
  },
  {
    id: "mauve",
    label: "Mauve (Tailwind)",
    ramp: {
      5: "#171218", // neutral-05
      10: "#251d26", // neutral-10
      20: "#3d323e", // neutral-20
      30: "#524554", // neutral-30
      40: "#665968", // neutral-40
      50: "#827583", // neutral-50
      60: "#9f94a0", // neutral-60
      70: "#b7adb8", // neutral-70
      80: "#d1c9d1", // neutral-80
      90: "#e8e5e8", // neutral-90
      95: "#f4f3f4", // neutral-95
    },
  },
  {
    id: "olive",
    label: "Olive (Tailwind)",
    ramp: {
      5: "#141410", // neutral-05
      10: "#212119", // neutral-10
      20: "#37372c", // neutral-20
      30: "#4b4b3d", // neutral-30
      40: "#5f5f4e", // neutral-40
      50: "#7b7b6a", // neutral-50
      60: "#99998a", // neutral-60
      70: "#b2b2a4", // neutral-70
      80: "#cdcdc2", // neutral-80
      90: "#e7e7e0", // neutral-90
      95: "#f3f3ef", // neutral-95
    },
  },
  {
    id: "mist",
    label: "Mist (Tailwind)",
    ramp: {
      5: "#111516", // neutral-05
      10: "#1b2123", // neutral-10
      20: "#2f383a", // neutral-20
      30: "#414c4f", // neutral-30
      40: "#536164", // neutral-40
      50: "#6f7d80", // neutral-50
      60: "#8e9b9e", // neutral-60
      70: "#a9b3b6", // neutral-70
      80: "#c6ced0", // neutral-80
      90: "#e3e7e8", // neutral-90
      95: "#f1f4f4", // neutral-95
    },
  },
  {
    id: "taupe",
    label: "Taupe (Tailwind)",
    ramp: {
      5: "#171312", // neutral-05
      10: "#251f1c", // neutral-10
      20: "#3d3431", // neutral-20
      30: "#534744", // neutral-30
      40: "#675b57", // neutral-40
      50: "#837772", // neutral-50
      60: "#a19591", // neutral-60
      70: "#b9afab", // neutral-70
      80: "#d2cac8", // neutral-80
      90: "#e9e5e4", // neutral-90
      95: "#f5f2f2", // neutral-95
    },
  },
] as const;
